improvement on user permission management
art-daq/otsdaq pull request #115
Opened 2023-10-20 21:46 UTC by antoniogioiosa

2023-10-23 18:59 UTC, rrivera747 requested changes

2023-10-23 18:59 UTC, rrivera747 commented on otsdaq/CoreSupervisors/CorePropertySupervisorBase.cc
> +	__SUP_COUT__ << "userInfo.requestType_ " << userInfo.requestType_ << __E__;
Please comment these printouts (line 512, 544-548) and also in WebUsers, put back to COUTT

2023-10-24 14:18 UTC, antoniogioiosa commented on otsdaq/CoreSupervisors/CorePropertySupervisorBase.cc
> +	__SUP_COUT__ << "userInfo.requestType_ " << userInfo.requestType_ << __E__;
Done

2023-10-24 14:35 UTC, rrivera747 approved these changes
Looks good!

2023-10-24 14:35 UTC, merged